<?xml version="1.0" encoding="UTF-8"?>
<project
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
  xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.github.otymko.dt.bsl.lsconnector</groupId>
    <artifactId>bundles</artifactId>
    <version>0.3.0-SNAPSHOT</version>
  </parent>

  <artifactId>com.github.otymko.dt.bsl.lspconnector</artifactId>
  <version>0.3.0-SNAPSHOT</version>
  <packaging>eclipse-plugin</packaging>

  <properties>
    <lombok.version>1.18.30</lombok.version>
    <bsl.ls.version>1.0.5</bsl.ls.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>${lombok.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.6.1</version>
        <executions>
          <execution>
            <id>get-lombok</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>org.projectlombok</groupId>
                  <artifactId>lombok</artifactId>
                  <version>${lombok.version}</version>
                  <type>jar</type>
                  <outputDirectory>${project.build.directory}</outputDirectory>
                  <destFileName>lombok.jar</destFileName>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>io.github.download-maven-plugin</groupId>
        <artifactId>download-maven-plugin</artifactId>
        <version>1.13.0</version>
        <executions>
          <execution>
            <id>get-bsl-ls</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>wget</goal>
            </goals>
            <configuration>
              <url>https://github.com/1c-syntax/bsl-language-server/releases/download/v${bsl.ls.version}/bsl-language-server-${bsl.ls.version}-exec.jar</url>
              <outputDirectory>${project.basedir}/lib</outputDirectory>
              <outputFileName>bsl-language-server-exec.jar</outputFileName>
              <overwrite>false</overwrite>
              <skipCache>false</skipCache>
              <readTimeOut>600000</readTimeOut>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-compiler-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>