name: Непрерывная интеграция

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Актуализация
        uses: actions/checkout@v4

      - name: Установка JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          # реджестри пакетов 1С
          server-id: dt_repository
          # назначается в сборке
          server-username: MAVEN_USERNAME
          # назначается в сборке
          server-password: MAVEN_CENTRAL_TOKEN # в открытом виде в секретах

      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-maven
      - name: Кеширование m2
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('targets/default/default.target') }}
          restore-keys: ${{ runner.os }}-m2

      # https://edt.1c.ru/dev/ru/docs/plugins/project/build-install-publish-project/
      - name: Загрузка lombok
        run: mvn dependency:copy@get-lombok -pl bundles/com.github.otymko.dt.bsl.lspconnector
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_OPTS: "-Djdk.xml.maxGeneralEntitySizeLimit=0 -Djdk.xml.totalEntitySizeLimit=0"

      - name: Сборка
        run: mvn verify -Dtycho.localArtifacts=ignore
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_OPTS: "-Djdk.xml.maxGeneralEntitySizeLimit=0 -Djdk.xml.totalEntitySizeLimit=0 -javaagent:${{ github.workspace }}/bundles/com.github.otymko.dt.bsl.lspconnector/target/lombok.jar=ECJ"
